# Generated by Django 3.0.2 on 2020-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('gbp_rate', models.FloatField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
