# Generated by Django 3.0.2 on 2020-01-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='gbp_rate',
            new_name='rate',
        ),
    ]
